---
platform: linux

image: docker:///datianshi/gradle

inputs:
  - name: music-repo
  - name: version

outputs:
  - name: build-artifact

run:
  path: music-repo/ci/tasks/build-artifact.sh
  args: [
    --input-dir,  music-repo,
    --output-dir, build-artifact
  ]
