---
platform: linux

image: docker:///datianshi/cf-cli

inputs:
  - name: common-lib-repo
  - name: common-lib-release

run:
  path: common-lib-repo/ci/tasks/cf-deployment.sh

params:
  API_ENDPOINT:
  USERNAME:
  PASSWORD:
  ORG:
  SPACE:
  HOST:
